"use client";

import { motion } from "framer-motion";
import { Sparkles, AlertTriangle, Info, ChevronDown } from "lucide-react";
import { getGradeColor } from "@/lib/utils";
import type { AiDiagnostic } from "@/lib/audit/types";
import { useState } from "react";

interface ScoreDisplayProps {
  score: number;
  grade: string;
  siteType: string;
  pagesAudited: number;
  url: string;
  aiMode?: "ai-enhanced" | "basic" | "ai-failed";
  aiDiagnostics?: AiDiagnostic[];
}

export function ScoreDisplay({ score, grade, siteType, pagesAudited, url, aiMode, aiDiagnostics }: ScoreDisplayProps) {
  const [showDiagnostics, setShowDiagnostics] = useState(false);
  const gradeColor = getGradeColor(grade);
  const strokeColor = score >= 80 ? "#10b981" : score >= 60 ? "#f59e0b" : "#ef4444";

  // SVG circle parameters
  const size = 160;
  const strokeWidth = 8;
  const radius = (size - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;
  const dashOffset = circumference - (score / 100) * circumference;

  const hasDiagnostics = aiDiagnostics && aiDiagnostics.length > 0;
  const showDiagnosticsToggle = aiMode !== "ai-enhanced" && hasDiagnostics;

  return (
    <div className="flex flex-col items-center gap-4 py-8">
      <p className="text-sm text-muted-foreground">
        {siteType} — {pagesAudited} pages audited
      </p>
      <p className="text-sm text-muted-foreground truncate max-w-md">{url}</p>

      {/* AI Mode Card */}
      {aiMode && (
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          className={`w-full max-w-sm rounded-lg border p-3 ${
            aiMode === "ai-enhanced"
              ? "border-accent/30 bg-accent/5"
              : aiMode === "ai-failed"
              ? "border-amber-500/30 bg-amber-500/5"
              : "border-border bg-muted/30"
          }`}
        >
          <div className="flex items-center gap-2">
            {aiMode === "ai-enhanced" ? (
              <>
                <Sparkles className="h-4 w-4 shrink-0 text-accent" />
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-medium text-accent">AI-Enhanced Analysis</p>
                  <p className="text-xs text-muted-foreground">Content, llms.txt, and JSON-LD generated by Claude</p>
                  {hasDiagnostics && (
                    <p className="mt-1 text-[10px] text-muted-foreground/70">
                      {aiDiagnostics.filter(d => d.success).length}/{aiDiagnostics.length} AI steps succeeded
                      {" — "}
                      {Math.round(aiDiagnostics.reduce((a, d) => a + d.durationMs, 0) / 1000)}s total
                    </p>
                  )}
                </div>
              </>
            ) : aiMode === "ai-failed" ? (
              <>
                <AlertTriangle className="h-4 w-4 shrink-0 text-amber-500" />
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-medium text-amber-600 dark:text-amber-400">AI Analysis Failed</p>
                  <p className="text-xs text-muted-foreground">API key is configured but AI calls failed — using deterministic fallbacks</p>
                </div>
              </>
            ) : (
              <>
                <Info className="h-4 w-4 shrink-0 text-muted-foreground" />
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-medium text-muted-foreground">Basic Mode</p>
                  <p className="text-xs text-muted-foreground">No API key detected — set ANTHROPIC_API_KEY for AI-enhanced results</p>
                </div>
              </>
            )}
          </div>

          {/* Diagnostics toggle */}
          {showDiagnosticsToggle && (
            <div className="mt-2">
              <button
                onClick={() => setShowDiagnostics(!showDiagnostics)}
                className="flex items-center gap-1 text-[11px] text-muted-foreground hover:text-foreground transition-colors"
                aria-expanded={showDiagnostics}
              >
                <ChevronDown className={`h-3 w-3 transition-transform ${showDiagnostics ? "rotate-180" : ""}`} />
                {showDiagnostics ? "Hide" : "Show"} diagnostics
              </button>

              {showDiagnostics && (
                <div className="mt-2 space-y-1.5 rounded-md bg-background/50 p-2 border border-border">
                  {aiDiagnostics!.map((d, i) => (
                    <div key={i} className="flex items-start gap-2 text-[11px]">
                      <span className={`mt-0.5 h-1.5 w-1.5 shrink-0 rounded-full ${d.success ? "bg-pass" : "bg-fail"}`} />
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2">
                          <span className="font-medium text-foreground">{d.step}</span>
                          <span className="text-muted-foreground/60">{d.durationMs}ms</span>
                        </div>
                        {d.error && (
                          <p className="mt-0.5 text-fail/80 break-words">{d.error}</p>
                        )}
                        <p className="text-muted-foreground/50">Model: {d.model}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Always show diagnostics for ai-enhanced mode if there were partial failures */}
          {aiMode === "ai-enhanced" && hasDiagnostics && aiDiagnostics.some(d => !d.success) && (
            <div className="mt-2">
              <button
                onClick={() => setShowDiagnostics(!showDiagnostics)}
                className="flex items-center gap-1 text-[11px] text-muted-foreground hover:text-foreground transition-colors"
                aria-expanded={showDiagnostics}
              >
                <ChevronDown className={`h-3 w-3 transition-transform ${showDiagnostics ? "rotate-180" : ""}`} />
                {aiDiagnostics.filter(d => !d.success).length} step(s) fell back to deterministic
              </button>

              {showDiagnostics && (
                <div className="mt-2 space-y-1.5 rounded-md bg-background/50 p-2 border border-border">
                  {aiDiagnostics.filter(d => !d.success).map((d, i) => (
                    <div key={i} className="flex items-start gap-2 text-[11px]">
                      <span className="mt-0.5 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-500" />
                      <div className="min-w-0 flex-1">
                        <span className="font-medium text-foreground">{d.step}</span>
                        {d.error && <span className="ml-1 text-muted-foreground">— {d.error}</span>}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </motion.div>
      )}

      <motion.div
        className="relative"
        initial={{ scale: 0.8, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        transition={{ duration: 0.5, ease: "easeOut" }}
      >
        <svg width={size} height={size} className="-rotate-90">
          <circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            fill="none"
            stroke="currentColor"
            strokeWidth={strokeWidth}
            className="text-muted"
          />
          <motion.circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            fill="none"
            stroke={strokeColor}
            strokeWidth={strokeWidth}
            strokeLinecap="round"
            strokeDasharray={circumference}
            initial={{ strokeDashoffset: circumference }}
            animate={{ strokeDashoffset: dashOffset }}
            transition={{ duration: 1.2, ease: "easeOut", delay: 0.3 }}
          />
        </svg>
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <motion.span
            className={`text-4xl font-bold ${gradeColor}`}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.8 }}
          >
            {grade}
          </motion.span>
          <motion.span
            className="text-lg text-muted-foreground"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.0 }}
          >
            {score}/100
          </motion.span>
        </div>
      </motion.div>
    </div>
  );
}
